AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for WebServer with Security Group and EC2 Instance

Parameters:
  Server1Tag: 
    Description: Enter Server1 Tag
    Type: String
    Default: DemoServer1

  Server2Tag: 
    Description: Enter Server2 Tag
    Type: String
    Default: DemoServer2 
  
  InstanceType: 
    Description: Select Instance Type for Server1
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.small
    - t2.micro
    - t2.nano 
    
Resources:
  EC2DemoServer1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04b4f1a9cf54c11d0
      InstanceType: !Ref InstanceType
      KeyName: sandy
      SecurityGroupIds: 
        - sg-0095fa0899cfb3387
      SubnetId: subnet-044828b5768fe4179
      Tags: 
        - Key: Name
          Value: !Ref Server1Tag

  EC2DemoServer2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04b4f1a9cf54c11d0
      InstanceType: t2.micro
      KeyName: sandy
      SecurityGroupIds: 
        - sg-0095fa0899cfb3387
      SubnetId: subnet-044828b5768fe4179
      Tags: 
        - Key: Name
          Value: !Ref Server2Tag